name: Build

on: 
  push:
    tags: [v*]
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build with nuitka
        run: |
          python -m nuitka --follow-imports --onefile --assume-yes-for-downloads app/weekexport.py
      - name: Package
        shell: powershell
        run:  |
          7z a weekExport_windows_x64.zip '${{github.workspace}}/weekexport.exe' '${{github.workspace}}/NOTICE.md'
      - uses: actions/upload-artifact@v3
        with:
          name: weekExport_windows_x64.zip
          path: weekExport_windows_x64.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            weekExport_windows_x64.zip
  build-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build with nuitka
        run: |
          python -m nuitka --follow-imports --onefile --macos-create-app-bundle --assume-yes-for-downloads app/weekexport.py
      - name: Update NOTICE
        shell: bash
        run:  |
          pip-licenses --with-urls --with-authors --with-description --format=markdown --output-file=./NOTICE.md
      - name: Package
        shell: bash
        run:  |
          tar czvf weekExport_mac_x64.tgz ${{github.workspace}}/weekexport.app ${{github.workspace}}/NOTICE.md
      - uses: actions/upload-artifact@v3
        with:
          name: weekExport_mac_x64.tgz
          path: weekExport_mac_x64.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            weekExport_mac_x64.tgz
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build with nuitka
        run: |
          python -m nuitka --follow-imports --onefile --assume-yes-for-downloads app/weekexport.py
      - name: Update NOTICE
        shell: bash
        run:  |
          pip-licenses --with-urls --with-authors --with-description --format=markdown --output-file=./NOTICE.md
      - name: Package
        shell: bash
        run:  |
          tar czvf weekExport_linux_x64.tgz ${{github.workspace}}/weekexport.bin ${{github.workspace}}/NOTICE.md
      - uses: actions/upload-artifact@v3
        with:
          name: weekExport_linux_x64.tgz
          path: weekExport_linux_x64.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            weekExport_linux_x64.tgz